name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: housfy/php-7.3-bitbucket-pipelines
          tag_with_ref: true
          tags: latest
